services:
  web:
    build: ./magnetlinks
    volumes:
      - ./magnetlinks:/magnetlinks # persistence volume
    ports:
      # bittorrent ports
      - "6881:6881"
      - "6891:6891"
    expose:
      - "8000"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./magnetlinks:/magnetlinks
    ports:
      - "8088:80"
    depends_on:
      - web
    env_file:
      - .env
    environment:
      - SERVER_NAME=${SERVER_NAME}

  redis:
    image: redis:alpine
    expose:
      - "6379"

  celery_worker:
    build: ./celery_worker
    volumes:
      - ./magnetlinks:/magnetlinks
    #command: celery -A magnetlinks worker --loglevel=info # moved to Dockerfile
    depends_on:
      - redis
      
  celery_beat:
    build: ./celery_beat
    #command: celery -A magnetlinks beat --loglevel=info --schedule=/var/lib/celery/celerybeat-schedule.db # moved to Dockerfile
    volumes:
      - ./magnetlinks:/magnetlinks
    depends_on:
      - redis
    
networks:
  default:
    driver: bridge