# Generated by Django 3.2.19 on 2024-10-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnetlinks', '0002_rename_image_magnetlink_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnetlink',
            name='leechers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magnetlink',
            name='seeders',
            field=models.IntegerField(default=0),
        ),
    ]
