# Generated by Django 3.2.19 on 2024-10-29 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnetlinks', '0003_auto_20241028_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magnetlink',
            name='hashfile',
        ),
    ]
