# Generated by Django 3.2.19 on 2024-10-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnetlinks', '0004_remove_magnetlink_hashfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnetlink',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
