# Generated by Django 3.2.19 on 2024-10-30 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magnetlinks', '0005_magnetlink_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnetlink',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
